name: upgrade-terraform

on:
  push:
jobs:
  upgrade-terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout uppjet
      uses: actions/checkout@v3
      with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
    - name: Checkout osc-k8s-rke-cluster
      uses: actions/checkout@v3
      with:
        repository: 'outscale-dev/osc-k8s-rke-cluster'
        path: "rke-cluster-for-upjet"
        ref: master
    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: v1.22.7
      id: install
    - name: Install golang
      uses: actions/setup-go@v3
      with:
        go-version: '1.19.7'
    - name: Install helm
      uses: azure/setup-helm@v3
      with:
        version: v3.10.1
    - name: Install python version
      uses: gabrielfalcao/pyenv-action@v11
      with:
        default: "3.10"
        command: pip install -U pip
    - name: Install deps
      run: |
        sudo pip3 install --ignore-installed -r requirements.txt
        sudo mkdir /root/.kube
        sudo touch /root/.kube/config
      env:
        git_full_local_path: /tmp/upjet-provider-outscale
        KUBECONFIG: /root/.kube/config
    - name: Clone Repository
      run: make clone
      env:
        git_full_local_path: /tmp/upjet-provider-outscale
        git_password: ${{ secrets.UPJET_TOKEN }}
    - name: Build and Push Docker Image
      run: |
        sudo apt-get update
        wget https://github.com/docker/buildx/releases/download/v0.10.4/buildx-v0.10.4.linux-amd64
        chmod +x buildx-v0.10.4.linux-amd64
        mv buildx-v0.10.4.linux-amd64 docker-buildx
        mv docker-buildx $HOME/.docker/cli-plugins
        make buildpush
      env:
        IMG: 127.0.0.1:4242/upjet-provider-outscale:${{ github.sha }}
        DOCKER_BUILDKIT: 1
        git_full_local_path: /tmp/upjet-provider-outscale
        git_password: ${{ secrets.UPJET_TOKEN }}

    