name: upgrade-terraform

on:
  push:
jobs:
  upgrade-terraform:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout uppjet
      uses: actions/checkout@v3
      with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
    - name: Checkout osc-k8s-rke-cluster
      uses: actions/checkout@v3
      with:
        repository: 'outscale-dev/osc-k8s-rke-cluster'
        path: "rke-cluster-for-upjet"
        ref: master
    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: v1.22.7
      id: install
    - name: Install golang
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.17.8'
    - name: Install helm
      uses: azure/setup-helm@v3
      with:
        version: v3.10.1

    - name: Install deps
      run: sudo pip3 install --ignore-installed -r requirements.txt
      env:
        git_full_local_path: /tmp/upjet-provider-outscale
    - name: Clone Repository
      run: make clone
      env:
        git_full_local_path: /tmp/upjet-provider-outscale
    - name: Build and Push Docker Image
      run: |
        sudo apt-get update
        sudo apt install -y docker-buildx-plugin 
        make buildpush
      env:
        IMG: 127.0.0.1:4242/upjet-provider-outscale:${{ github.sha }}
        DOCKER_BUILDKIT: 1
    